language: java
jdk:
- openjdk8

services:
- docker

branches:
  only:
  - master
  - development

install: ./gradlew install dockerBuildImage
script:
- export VERSION=$(grep "TS_HLA_BaseVersion" ./.shared/libraries.gradle | awk '{print $3}' | tr -d \')
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- docker tag ivct/ts-hla-encoding-rules:2.0.0 ivct/ts-hla-encoding-rules:$TRAVIS_BRANCH-latest
- docker tag ivct/ts-hla-cs-verification:2.0.0 ivct/ts-hla-cs-verification:$TRAVIS_BRANCH-latest
- docker tag ivct/ts-hla-declaration:2.0.0 ivct/ts-hla-declaration:$TRAVIS_BRANCH-latest
- docker tag ivct/ts-hla-object:2.0.0 ivct/ts-hla-object:$TRAVIS_BRANCH-latest
- docker tag ivct/ts-hla-services:2.0.0 ivct/ts-hla-services:$TRAVIS_BRANCH-latest
- docker push ivct/ts-hla-encoding-rules
- docker push ivct/ts-hla-cs-verification
- docker push ivct/ts-hla-declaration
- docker push ivct/ts-hla-object
- docker push ivct/ts-hla-services

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
